export function getSource() {
    return [
                { title: 'EUR_ZAR', description: 'EUR/ZAR', price: 'FX' },
                { title: 'EUR_HUF', description: 'EUR/HUF', price: 'FX' },
                { title: 'EUR_NOK', description: 'EUR/NOK', price: 'FX' },
                { title: 'USD_HUF', description: 'USD/HUF', price: 'FX' },
                { title: 'GBP_ZAR', description: 'GBP/ZAR', price: 'FX' },
                { title: 'NZD_SGD', description: 'NZD/SGD', price: 'FX' },
                { title: 'CAD_JPY', description: 'CAD/JPY', price: 'FX' },
                { title: 'EUR_USD', description: 'EUR/USD', price: 'FX' },
                { title: 'EUR_JPY', description: 'EUR/JPY', price: 'FX' },
                { title: 'NZD_CHF', description: 'NZD/CHF', price: 'FX' },
                { title: 'USD_CAD', description: 'USD/CAD', price: 'FX' },
                { title: 'AUD_CAD', description: 'AUD/CAD', price: 'FX' },
                { title: 'NZD_USD', description: 'NZD/USD', price: 'FX' },
                { title: 'HKD_JPY', description: 'HKD/JPY', price: 'FX' },
                { title: 'CHF_JPY', description: 'CHF/JPY', price: 'FX' },
                { title: 'CAD_CHF', description: 'CAD/CHF', price: 'FX' },
                { title: 'CAD_SGD', description: 'CAD/SGD', price: 'FX' },
                { title: 'EUR_SGD', description: 'EUR/SGD', price: 'FX' },
                { title: 'EUR_TRY', description: 'EUR/TRY', price: 'FX' },
                { title: 'USD_JPY', description: 'USD/JPY', price: 'FX' },
                { title: 'CHF_HKD', description: 'CHF/HKD', price: 'FX' },
                { title: 'SGD_HKD', description: 'SGD/HKD', price: 'FX' },
                { title: 'GBP_HKD', description: 'GBP/HKD', price: 'FX' },
                { title: 'EUR_CHF', description: 'EUR/CHF', price: 'FX' },
                { title: 'EUR_SEK', description: 'EUR/SEK', price: 'FX' },
                { title: 'USD_SGD', description: 'USD/SGD', price: 'FX' },
                { title: 'GBP_PLN', description: 'GBP/PLN', price: 'FX' },
                { title: 'EUR_NZD', description: 'EUR/NZD', price: 'FX' },
                { title: 'NZD_JPY', description: 'NZD/JPY', price: 'FX' },
                { title: 'AUD_USD', description: 'AUD/USD', price: 'FX' },
                { title: 'USD_PLN', description: 'USD/PLN', price: 'FX' },
                { title: 'GBP_AUD', description: 'GBP/AUD', price: 'FX' },
                { title: 'GBP_USD', description: 'GBP/USD', price: 'FX' },
                { title: 'USD_MXN', description: 'USD/MXN', price: 'FX' },
                { title: 'USD_CNH', description: 'USD/CNH', price: 'FX' },
                { title: 'TRY_JPY', description: 'TRY/JPY', price: 'FX' },
                { title: 'GBP_CHF', description: 'GBP/CHF', price: 'FX' },
                { title: 'USD_THB', description: 'USD/THB', price: 'FX' },
                { title: 'EUR_DKK', description: 'EUR/DKK', price: 'FX' },
                { title: 'AUD_NZD', description: 'AUD/NZD', price: 'FX' },
                { title: 'EUR_AUD', description: 'EUR/AUD', price: 'FX' },
                { title: 'GBP_NZD', description: 'GBP/NZD', price: 'FX' },
                { title: 'SGD_JPY', description: 'SGD/JPY', price: 'FX' },
                { title: 'EUR_PLN', description: 'EUR/PLN', price: 'FX' },
                { title: 'USD_NOK', description: 'USD/NOK', price: 'FX' },
                { title: 'AUD_HKD', description: 'AUD/HKD', price: 'FX' },
                { title: 'USD_DKK', description: 'USD/DKK', price: 'FX' },
                { title: 'NZD_HKD', description: 'NZD/HKD', price: 'FX' },
                { title: 'USD_CZK', description: 'USD/CZK', price: 'FX' },
                { title: 'EUR_HKD', description: 'EUR/HKD', price: 'FX' },
                { title: 'USD_CHF', description: 'USD/CHF', price: 'FX' },
                { title: 'USD_HKD', description: 'USD/HKD', price: 'FX' },
                { title: 'SGD_CHF', description: 'SGD/CHF', price: 'FX' },
                { title: 'NZD_CAD', description: 'NZD/CAD', price: 'FX' },
                { title: 'AUD_SGD', description: 'AUD/SGD', price: 'FX' },
                { title: 'EUR_CZK', description: 'EUR/CZK', price: 'FX' },
                { title: 'AUD_JPY', description: 'AUD/JPY', price: 'FX' },
                { title: 'USD_INR', description: 'USD/INR', price: 'FX' },
                { title: 'CAD_HKD', description: 'CAD/HKD', price: 'FX' },
                { title: 'USD_ZAR', description: 'USD/ZAR', price: 'FX' },
                { title: 'GBP_JPY', description: 'GBP/JPY', price: 'FX' },
                { title: 'USD_TRY', description: 'USD/TRY', price: 'FX' },
                { title: 'ZAR_JPY', description: 'ZAR/JPY', price: 'FX' },
                { title: 'GBP_CAD', description: 'GBP/CAD', price: 'FX' },
                { title: 'USD_SAR', description: 'USD/SAR', price: 'FX' },
                { title: 'EUR_CAD', description: 'EUR/CAD', price: 'FX' },
                { title: 'GBP_SGD', description: 'GBP/SGD', price: 'FX' },
                { title: 'USD_SEK', description: 'USD/SEK', price: 'FX' },
                { title: 'CHF_ZAR', description: 'CHF/ZAR', price: 'FX' },
                { title: 'EUR_GBP', description: 'EUR/GBP', price: 'FX' },
                { title: 'AUD_CHF', description: 'AUD/CHF', price: 'FX' },
                { title: 'XCU_USD', description: 'XCU/USD', price: 'CFD' },
                { title: 'XAG_GBP', description: 'XAG/GBP', price: 'CFD' },
                { title: 'XAG_HKD', description: 'XAG/HKD', price: 'CFD' },
                { title: 'XAU_HKD', description: 'XAU/HKD', price: 'CFD' },
                { title: 'XAU_CAD', description: 'XAU/CAD', price: 'CFD' },
                { title: 'XAU_SGD', description: 'XAU/SGD', price: 'CFD' },
                { title: 'XAU_AUD', description: 'XAU/AUD', price: 'CFD' },
                { title: 'XAG_CAD', description: 'XAG/CAD', price: 'CFD' },
                { title: 'XAU_CHF', description: 'XAU/CHF', price: 'CFD' },
                { title: 'XAU_NZD', description: 'XAU/NZD', price: 'CFD' },
                { title: 'XPD_USD', description: 'XPD/USD', price: 'CFD' },
                { title: 'XPT_USD', description: 'XPT/USD', price: 'CFD' },
                { title: 'XAG_NZD', description: 'XAG/NZD', price: 'CFD' },
                { title: 'XAG_JPY', description: 'XAG/JPY', price: 'CFD' },
                { title: 'XAU_EUR', description: 'XAU/EUR', price: 'CFD' },
                { title: 'XAG_CHF', description: 'XAG/CHF', price: 'CFD' },
                { title: 'XAU_XAG', description: 'XAU/XAG', price: 'CFD' },
                { title: 'XAG_USD', description: 'XAG/USD', price: 'CFD' },
                { title: 'XAG_EUR', description: 'XAG/EUR', price: 'CFD' },
                { title: 'XAU_JPY', description: 'XAU/JPY', price: 'CFD' },
                { title: 'XAG_AUD', description: 'XAG/AUD', price: 'CFD' },
                { title: 'XAU_GBP', description: 'XAU/GBP', price: 'CFD' },
                { title: 'XAU_USD', description: 'XAU/USD', price: 'CFD' },
                { title: 'XAG_SGD', description: 'XAG/SGD', price: 'CFD' },
                { title: 'BCO_USD', description: 'BCO/USD', price: 'CFD' },
                { title: 'WTICO_USD', description: 'WTICO', price: 'CFD' },
                { title: 'NATGAS_USD', description: 'NATGAS', price: 'CFD' },
                { title: 'SUGAR_USD', description: 'SUGAR', price: 'CFD' },
                { title: 'SOYBN_USD', description: 'SOY BEAN', price: 'CFD' },
                { title: 'CORN_USD', description: 'CORN', price: 'CFD' },
                { title: 'WHEAT_USD', description: 'WHEAT', price: 'CFD' },
                { title: 'DE30_EUR', description: 'DE30', price: 'INDICES' },
                { title: 'NAS100_USD', description: 'NASDAQ', price: 'INDICES' },
                { title: 'NL25_EUR', description: 'NL25', price: 'INDICES' },
                { title: 'SG30_SGD', description: 'SINGAPORE 30', price: 'INDICES' },
                { title: 'UK100_GBP', description: 'UK 100', price: 'INDICES' },
                { title: 'AU200_AUD', description: 'AU 200', price: 'INDICES' },
                { title: 'IN50_USD', description: 'IN 50', price: 'INDICES' },
                { title: 'JP225_USD', description: 'JP 225', price: 'INDICES' },
                { title: 'FR40_EUR', description: 'FR 40', price: 'INDICES' },
                { title: 'EU50_EUR', description: 'EU 50', price: 'INDICES' },
                { title: 'SPX500_USD', description: 'SPX 500', price: 'INDICES' },
                { title: 'US30_USD', description: 'US 30', price: 'INDICES' },
                { title: 'TWIX_USD', description: 'TWIX_USD', price: 'INDICES' },
                { title: 'CN50_USD', description: 'CN50_USD', price: 'INDICES' },
                { title: 'HK33_HKD', description: 'HK 33', price: 'INDICES' },
                { title: 'US2000_USD', description: 'US 2000', price: 'INDICES' },
                { title: 'DE10YB_EUR', description: 'DE10YB_EUR', price: 'BONDS' },
                { title: 'USB10Y_USD', description: 'USB10Y_USD', price: 'BONDS' },
                { title: 'USB30Y_USD', description: 'USB30Y_USD', price: 'BONDS' },
                { title: 'UK10YB_GBP', description: 'UK10YB_GBP', price: 'BONDS' },
                { title: 'USB05Y_USD', description: 'USB05Y_USD', price: 'BONDS' },
                { title: 'USB02Y_USD', description: 'USB02Y_USD', price: 'BONDS' }
            ]
}
